/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_josuerocha;

import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.Random;

/**
 *
 * @author josue
 */
public class Popeyes extends javax.swing.JFrame {

    private ArrayList complementos = new ArrayList<String>();
    private Random r = new Random();

    /**
     * Creates new form Popeyes
     */
    public Popeyes() {
        initComponents();
        ab = new adminbarra(progress,piezas,complementos);

        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) complements.getModel();
        modelo.addElement("Biscuits");
        modelo.addElement("Pure");
        modelo.addElement("Papas");
        modelo.addElement("Refresco");
        modelo.addElement("Pie");
        complements.setModel(modelo);
        MemoriaClientes mp = new MemoriaClientes("./Clientes.jarp");
        mp.cargarArchivo();
        DefaultListModel modelo5
                = new DefaultListModel();
        for (Clientes c : mp.getListaClientes()) {
            modelo5.addElement(c);
        }
        ordenlist.setModel(modelo5);
        DefaultTableModel t = new DefaultTableModel();
        String[] titulo = new String[]{"# DE ORDEN", "ELEMENTO", "TIEMPO"};
        t.setColumnIdentifiers(titulo);
        tablaorden.setModel(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listahistorial = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordenlist = new javax.swing.JList<>();
        jPanel1 = new FondoPane1();
        jLabel1 = new javax.swing.JLabel();
        historial = new javax.swing.JButton();
        helpbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        piezas = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        complements = new javax.swing.JComboBox<>();
        addcomplement = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaorden = new javax.swing.JTable();
        progress = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        order = new javax.swing.JButton();

        ordenlist.setBackground(new java.awt.Color(153, 0, 51));
        ordenlist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ordenlist.setForeground(new java.awt.Color(51, 51, 51));
        ordenlist.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(ordenlist);

        javax.swing.GroupLayout listahistorialLayout = new javax.swing.GroupLayout(listahistorial.getContentPane());
        listahistorial.getContentPane().setLayout(listahistorialLayout);
        listahistorialLayout.setHorizontalGroup(
            listahistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listahistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        listahistorialLayout.setVerticalGroup(
            listahistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listahistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("BIENVENIDO");

        historial.setBackground(new java.awt.Color(255, 255, 0));
        historial.setForeground(new java.awt.Color(51, 51, 51));
        historial.setText("HISTORIAL");
        historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialMouseClicked(evt);
            }
        });

        helpbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info_64.png"))); // NOI18N
        helpbutton.setText(" ");
        helpbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        helpbutton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info_32.png"))); // NOI18N
        helpbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpbuttonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("NOMBRE");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("REALIZAR ORDEN");

        namefield.setText(" ");
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("AYUDA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("PIEZAS DE POLLO");

        piezas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 32, 1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("COMPLEMENTOS");

        complements.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        complements.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        addcomplement.setBackground(new java.awt.Color(0, 0, 204));
        addcomplement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addcomplement.setForeground(new java.awt.Color(255, 255, 0));
        addcomplement.setText("AGREGAR");
        addcomplement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcomplementMouseClicked(evt);
            }
        });
        addcomplement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcomplementActionPerformed(evt);
            }
        });

        tablaorden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaorden);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("ORDEN");

        order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pollo_62.png"))); // NOI18N
        order.setText("ORDENAR");
        order.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pollo_48.png"))); // NOI18N
        order.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pollo_72.png"))); // NOI18N
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(historial)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(piezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(27, 27, 27)
                                    .addComponent(complements, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(addcomplement))
                                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4))
                                    .addComponent(helpbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(helpbutton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(piezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(complements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addcomplement))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(order)
                        .addGap(18, 18, 18)
                        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(historial)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void addcomplementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcomplementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addcomplementActionPerformed

    private void addcomplementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcomplementMouseClicked
        if (complements.getSelectedIndex() > 0) {
            complementos.add((String) complements.getSelectedItem());
        }
        JOptionPane.showMessageDialog(this, "Complemento agregado a su orden");
    }//GEN-LAST:event_addcomplementMouseClicked

    private void helpbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpbuttonMouseClicked
        JOptionPane.showMessageDialog(this, "En esta ventana usted puede hacer una orden que llegara directo a su hogar!\nPara ordenar simplemente tiene que seguir estos sencillos pasos:\n\n1-Ingrese su nombre,la cantidad de piezas de pollo que desea,y los complementos que desea.\n"
                + "2-Si usted desea mas de un complemento, presione el boton de agregar cuantas veces necesite.\n"
                + "(Se le agregara a su orden el complemento seleccionado en la lista cada vez que usted presione agregar)"
                + "\n3-Presione Ordenar una vez que haya concluido y espere a que su orden se procese.");
    }//GEN-LAST:event_helpbuttonMouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked

        ab.start();
        Date fecha = new Date();
        int nr = 1 + r.nextInt(99999);
        int pieces = (int) piezas.getValue();
        String nombre = namefield.getText();
        ArrayList<String> complements = complementos;
        try {
            DefaultListModel modelo = (DefaultListModel) ordenlist.getModel();
            Ordenes o = new Ordenes(pieces, complements);
            Clientes c = new Clientes(o, nombre);
            modelo.addElement(c);
            ordenlist.setModel(modelo);
            namefield.setText("");
            MemoriaClientes ap = new MemoriaClientes("./Clientes.jarp");
            ap.cargarArchivo();
            ap.setCliente(c);
            ap.escribirArchivo();
            FileWriter fw = null;
            BufferedWriter bw = null;
            File archivo = null;
            try {
                archivo = new File("./" + "Factura" + nr + ".txt");
                fw = new FileWriter(archivo, false);
                bw = new BufferedWriter(fw);
                bw.write("Fecha: " + fecha.toString());
                bw.newLine();
                bw.write("Cliente: " + nombre);
                bw.newLine();
                bw.write("Numero de orden: #" + nr);
                bw.newLine();
                bw.write("Piezas de pollo ordenadas: " + pieces);
                bw.newLine();
                bw.write("Complementos ordenados: " + complements.size() + ": ");
                for (String com : complements) {
                    bw.write(com);
                    bw.write(", ");
                }
                bw.newLine();
                bw.write("Vuelva Pronto!!!");
                bw.flush();
            } catch (Exception ex) {
            }
            bw.close();
            fw.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        complementos.clear();
        JOptionPane.showMessageDialog(this, "ORDEN COMPLETADA!!!");


    }//GEN-LAST:event_orderMouseClicked

    private void historialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialMouseClicked
        listahistorial.setModal(true);
        listahistorial.pack();
        listahistorial.setLocationRelativeTo(this);
        listahistorial.setVisible(true);
    }//GEN-LAST:event_historialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popeyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popeyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popeyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popeyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popeyes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcomplement;
    private javax.swing.JComboBox<String> complements;
    private javax.swing.JButton helpbutton;
    private javax.swing.JButton historial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog listahistorial;
    private javax.swing.JTextField namefield;
    private javax.swing.JList<String> ordenlist;
    private javax.swing.JButton order;
    private javax.swing.JSpinner piezas;
    private javax.swing.JProgressBar progress;
    private javax.swing.JTable tablaorden;
    // End of variables declaration//GEN-END:variables

    adminbarra ab;

    class FondoPane1 extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/popeyes.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);

        }
    }

}
